package com.inthergroup.internship.models;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * An entity Benefit composed by two fields (id, name). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author interns
 */
@Entity
@Table(name = "benefit_types")
public class BenefitType {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    /**
     *  An autogenerated id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(length = 20)
    private long id;
    
    @Column(nullable = false, unique = true)
    private String name;
    
    /**
     * Benefits for a specific level
     */
    @OneToMany(mappedBy = "primaryKey.benefitType", orphanRemoval = true,
            cascade = CascadeType.ALL)
    private Set<CareerLevelBenefit> careerLevelBenefits = new HashSet<CareerLevelBenefit>();
    
    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public BenefitType() {
    }

    public BenefitType(long id) {
        this.id = id;
    }
    
    public BenefitType(String name) {
        this.name = name;
    }

    public BenefitType(long id, String name) {
        this.id = id;
        this.name = name;
    }
    
    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<CareerLevelBenefit> getCareerLevelBenefits() {
        return careerLevelBenefits;
    }

    public void setCareerLevelBenefits(Set<CareerLevelBenefit> careerLevelBenefits) {
        this.careerLevelBenefits = careerLevelBenefits;
    }
}
