package com.inthergroup.internship.models;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * An entity Benefits composed by two fields (id, benefitName). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author interns
 */
@Entity
@Table(name = "benefits")
public class Benefit {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    
    private String benefitName;
    
    @ManyToMany(mappedBy="benefits")
    private List<User> users;
    
    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public Benefit() {
    }

    public Benefit(long id) {
        this.id = id;
    }
    
    public Benefit(String benefitName) {
        this.benefitName = benefitName;
    }

    public Benefit(long id, String benefitName) {
        this.id = id;
        this.benefitName = benefitName;
    }
    
    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getBenefitName() {
        return benefitName;
    }

    public void setBenefitName(String benefitName) {
        this.benefitName = benefitName;
    }

    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }
    
    public void addUser(User user) {        
        users.add(user);
        
        if (!user.getBenefits().contains(this)) { // warning this may cause performance issues if you have a large data set since this operation is O(n)
            user.getBenefits().add(this);
        }
    }
}
