package com.inthergroup.internship.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity GroupsUsers composed by three fields (id, groupId, userId).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author interns
 */
@Entity
@Table(name = "groups_users")
public class GroupsUsers {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    
    // An autogenerated id
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    
    @NotNull
    private long groupId;
    
    @NotNull
    private long userId;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    
    public GroupsUsers() { }
    
    public GroupsUsers(long id) {
        this.id = id;
    }
    
    public GroupsUsers(long groupId, long userId) {
        super();
        this.groupId = groupId;
        this.userId = userId;
    }
    
    // Getter and setter methods
    
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
    
    public long getGroupId() {
        return groupId;
    }

    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }    
    
} // class GroupsUsers
