package com.inthergroup.internship.models;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * An entity Group composed by two fields (id, name). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author interns
 */
@Entity
@Table(name = "groups")
public class Group {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    /**
     *  An autogenerated id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(length = 20)
    private long id;
    
    @Column(nullable = false, unique = true)
    private String role;
    
    /**
     * Users belonging to this group.
     */
    @OneToMany(mappedBy="group")
    private List<User> users = new ArrayList<User>();

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public Group() {
    }

    public Group(long id) {
        super();
        this.id = id;
    }
    
    public Group(String name) {
        this.role = name;
    }

    public Group(long id, String name) {
        this.id = id;
        this.role = name;
    }
    
    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }
    
    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }
    
    public void addUser(User user) {
        this.users.add(user);
        if (user.getGroup() != this) {
            user.setGroup(this);
        }
    }

} // class Groups
