package com.inthergroup.internship.models;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * An entity Todo composed by two fields (id, benefitName). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author interns
 */
@Entity
@Table(name = "todo_types")
public class TodoType {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(length = 20)
    private long id;
    
    @Column(nullable = false, unique = true)
    private String name;
    
//    @Column(nullable = false, columnDefinition = "integer default 1")
//    private int quantity;
    
//    @Column(nullable = false, columnDefinition = "boolean default false")
//    private boolean done;
    
//    @ManyToMany(mappedBy="todos")
//    private List<User> users;
    
//    @OneToMany(mappedBy="todo", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
//    private List<UserTodoAssociation> users;
    
//    // TODO change to many-to-many with extra columns
//    // The TodoType's todos
//    @OneToMany(mappedBy = "primaryKey.todoType", orphanRemoval=true,
//            cascade = CascadeType.ALL)
//    private Set<Todo> userTodos = new HashSet<Todo>();
    
    // TODO change to many-to-many with extra columns
    @ManyToMany(mappedBy="todos")
    private List<CareerLevel> careerLevels;
    
    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public TodoType() { }

    public TodoType(long id) {
        this.id = id;
    }
    
    public TodoType(String name) {
        this.name = name;
    }

    public TodoType(long id, String name) {
        this.id = id;
        this.name = name;
    }
    
    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // This code snippet is for old implementation of User class.
    // But it can be useful for creating a new code.
    //  public void addUser(User user) {        
    //  users.add(user);
    //  
    //  if (!user.getTodos().contains(this)) { // warning this may cause performance issues if you have a large data set since this operation is O(n)
    //      user.getTodos().add(this);
    //  }
    //}
//
//    public Set<Todo> getUserTodos() {
//        return userTodos;
//    }
//
//    public void setUserTodos(Set<Todo> userTodos) {
//        this.userTodos = userTodos;
//    }

    public List<CareerLevel> getCareerLevels() {
        return careerLevels;
    }

    public void setCareerLevels(List<CareerLevel> careerLevels) {
        this.careerLevels = careerLevels;
    }
}
