package com.inthergroup.internship.models;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * An entity Todo composed by two fields (id, benefitName). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author interns
 */
@Entity
@Table(name = "todos")
public class Todo {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(length = 20)
    private long id;
    
    @Column(nullable = false, unique = true)
    private String task;
    
//    @Column(nullable = false, columnDefinition = "boolean default false")
//    private boolean done;
    
//    @ManyToMany(mappedBy="todos")
//    private List<User> users;
    
//    @OneToMany(mappedBy="todo", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
//    private List<UserTodoAssociation> users;
    
    // The todo's userTodos
    @OneToMany(mappedBy = "primaryKey.todo", orphanRemoval=true,
            cascade = CascadeType.ALL)
    private Set<UserTodo> userTodos = new HashSet<UserTodo>();
    
    @ManyToMany(mappedBy="todos")
    private List<CareerLevel> careerLevels;
    
    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public Todo() { }

    public Todo(long id) {
        this.id = id;
    }
    
    public Todo(String task) {
        this.task = task;
    }

    public Todo(long id, String task) {
        this.id = id;
        this.task = task;
    }
    
    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTask() {
        return task;
    }

    public void setTask(String task) {
        this.task = task;
    }

    
    
    // This code snippet is for old implementation of User class.
    // But it can be useful for creating a new code.
    //  public void addUser(User user) {        
    //  users.add(user);
    //  
    //  if (!user.getTodos().contains(this)) { // warning this may cause performance issues if you have a large data set since this operation is O(n)
    //      user.getTodos().add(this);
    //  }
    //}

    public Set<UserTodo> getUserTodos() {
        return userTodos;
    }

    public void setUserTodos(Set<UserTodo> userTodos) {
        this.userTodos = userTodos;
    }

    public List<CareerLevel> getCareerLevels() {
        return careerLevels;
    }

    public void setCareerLevels(List<CareerLevel> careerLevels) {
        this.careerLevels = careerLevels;
    }
}
