package com.inthergroup.internship.models;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * An entity Todo composed by two fields (id, name). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author interns
 */
@Entity
@Table(name = "todo_types")
public class TodoType {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    /**
     *  An autogenerated id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(length = 20)
    private long id;
    
    @Column(nullable = false, unique = true)
    private String name;
    
    /**
     * Tasks for a specific level
     */
    @OneToMany(mappedBy = "primaryKey.todoType", orphanRemoval=true,
            cascade = CascadeType.ALL)
    private Set<CareerLevelTodo> careerLevelTodos = new HashSet<CareerLevelTodo>();
    
    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public TodoType() { }

    public TodoType(long id) {
        this.id = id;
    }
    
    public TodoType(String name) {
        this.name = name;
    }

    public TodoType(long id, String name) {
        this.id = id;
        this.name = name;
    }
    
    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<CareerLevelTodo> getCareerLevelTodos() {
        return careerLevelTodos;
    }

    public void setCareerLevelTodos(Set<CareerLevelTodo> careerLevelTodos) {
        this.careerLevelTodos = careerLevelTodos;
    }
}
