package com.inthergroup.internship.models;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * An entity Todo composed by two fields (id, benefitName). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author interns
 */
@Entity
@Table(name = "todos")
public class Todo {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(length = 20)
    private long id;
    
    @Column(nullable = false, unique = true)
    private String task;
    
//    @Column(nullable = false, columnDefinition = "boolean default false")
//    private boolean done;
    @ManyToMany(mappedBy="todos")
    private List<User> users;
    
    @ManyToMany(mappedBy="todos")
    private List<CareerLevel> careerLevels;
    
    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public Todo() {
    }

    public Todo(long id) {
        this.id = id;
    }
    
    public Todo(String task) {
        this.task = task;
    }

    public Todo(long id, String task) {
        this.id = id;
        this.task = task;
    }
    
    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTask() {
        return task;
    }

    public void setTask(String task) {
        this.task = task;
    }
    
    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }
    
    public void addUser(User user) {        
        users.add(user);
        
        if (!user.getTodos().contains(this)) { // warning this may cause performance issues if you have a large data set since this operation is O(n)
            user.getTodos().add(this);
        }
    }

    public List<CareerLevel> getCareerLevels() {
        return careerLevels;
    }

    public void setCareerLevels(List<CareerLevel> careerLevels) {
        this.careerLevels = careerLevels;
    }
}
