package com.inthergroup.internship.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * An entity UserBenefits composed by two fields (id, benefitName). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author interns
 */
@Deprecated
@Entity
@Table(name = "users_benefits")
public class UserBenefit {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    private long userId;
    private long benefitId;
    
    // ------------------------
    // PUBLIC METHODS
    // ------------------------


    public UserBenefit() {
    }

    public UserBenefit(long id) {
        this.id = id;
    }

    public UserBenefit(long id, long userId, long benefitId) {
        this.id = id;
        this.userId = userId;
        this.benefitId = benefitId;
    }
    
    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getBenefitId() {
        return benefitId;
    }

    public void setBenefitId(long benefitId) {
        this.benefitId = benefitId;
    }

}
